#+title: Элементы Функциональных Языков

* Вывод типов (Type inference)
Синтаксическая структура программы позволяет составить систему уравнений относительно типов ее частей, автоматическое решение которой избавляет программиста от необходимости явно указывать типы.
#+begin_src 
dot(v1,v2) = v1[0]*v2[0] + v1[1]*v2[1]
#+end_src

Выводом типов называется автоматическое полное или частичное вычисление типов некоторых выражений программы, основанное лишь на ее синтаксической структуре и производимое статически, без необходимости запуска программы.
Исходная информация для алгоритма вывода типов — сама программа, способ присваивания типов литералам (таким как 42.0f, “hello”, и т. п.), типы некоторых функций и значений, а также правила типизации синтаксических конструкций (типы встроенных арифметических операций, типы операций доступа к структурам данных, взятые из определений этих структур, и т. п.).

* Функция высшего порядка (ФВП) (Higher-order function (HOF))
Функция, принимающая на вход или возвращающая функцию.
Оператор вычисления производной является функцией высшего порядка: он действует над функциями, и к тому же, его результатом является также функция. В программировании самые ранние из объектов, схожих с функциями высшего порядка — это «комбинаторы» в комбинаторной логике и термы в нетипизированном лямбда-исчислении.
Первым языком программирования с поддержкой функций высшего порядка оказался появившийся еще в 1958 году LISP, изначально являвшийся в первую очередь реализацией лямбда-исчисления.
Функции высшего порядка позволяют уменьшить избыточность в программе и сократить код, что положительно влияет на корректность (меньше мест для совершения ошибки — меньше ошибок) и поддерживаемость (не надо делать изменения во множестве похожих мест в коде: достаточно изменить код, абстрагирующий их сходство).

* Замыкание (Closure)
Функция, использующая переменные из области видимости, в которой была создана.
Замыкание — это пара из лямбда-выражения («кода») со свободными переменными и окружения, связывающего их. Внутри замыкания все переменные связаны, т. е. оно замкнуто. Первая полноценная реализация лексических замыканий относится к языку Scheme (диалект LISP, 1975 г.).
#+begin_src 
def fetcher(dict):
   def fetch(k):
     return dict[k]
   return fetch

def values(dict, keys):
  return map(fetcher(dict), keys)
#+end_src

* Частичное применение, карринг и сечения (Partial application, currying and sections)
Фиксацией некоторых аргументов из функции получается новая функция с меньшим числом аргументов.

#+begin_src 
matchesRegexp :: String -> String -> Bool
matchesRegexp pattern string = ...

isNumber s = matchesRegexp "-?[0-9]+" s
#+end_src

Частичным применением n-арной функции f называется конструкция, значением которой является (n−k)-арная функция, соответствующая f при фиксированных значениях некоторых k из n аргументов.

* Бесточечный стиль (Point-free style)
Сборка функций из других функций при помощи комбинаторов, без явного упоминания аргументов.
Часто для задания функции не нужно описывать, как она действует на абстрактный аргумент, а можно выразить ее действие в целом, не обращаясь к существительным, обозначающим ее аргументы.
При бесточечном стиле функции по возможности не определяются через результат вычислений над их аргументами (следовательно, анонимные лямбда-выражения тоже не используются). Вместо этого функции выражаются через другие функции при помощи комбинаторов высшего порядка и о функциях высшего порядка.

#+begin_src 
-- Ширина окна = наибольшая ширина составляющих:
frameWidth = maximum . map componentWidth . windowContents
#+end_src

* Хвостовой вызов (Tail call)
Применение функции, соответствующее замене одной вычислительной задачи на другую, вместо сведения одной задачи к другой.

* Чисто функциональная структура данных (Purely functional data structure)
Вместо изменения структуры данных можно формировать новую структуру, немного отличающуюся от старой.
Чисто функциональная структура данных — это структура данных, которую нельзя изменить, но на основе которой можно создать новую структуру данных, немного отличающуюся от первой.

Один из примеров использования чисто функциональных структур данных - они чрезвычайно удобны для реализации комбинаторного перебора с откатами. Чисто функциональные структуры идеально подходят для многопоточного использования, поскольку у них по определению отсутствуют проблемы с одновременными чтениями/изменениями - экземпляр структуры всегда можно использовать из нескольких потоков, и из любого потока любой экземпляр всегда виден в целостном состоянии.

* Алгебраический (индуктивный) тип данных (Algebraic (inductive) datatype)
Тип данных, состоящий из нескольких различимых разновидностей (возможно, составных) термов (значений).

Алгебраические типы позволяют определять типы-произведения (кортежи).
Под термином «тип-произведение» в данном случае имеется в виду, что тип FileInfo соответствует декартову произведению множеств,
соответствующих его компонентам.
#+begin_src 
data FileInfo where
   FileInfo { name::String,
              accessRights::Int,
              lastModified::Date } :: FileInfo
#+end_src

Алгебраические типы позволяют определять типы-суммы.
Под термином «тип-сумма» в данном случае имеется в виду, что множество термов, имеющих тип Color, складывается из термов вида «Red», «Green», «Blue», «Yellow».
#+begin_src 
data Color where
   Red :: Color
   Orange :: Color
   Yellow :: Color
   Green :: Color
   Blue :: Color
#+end_src

Пример:
Итак, существует 3 типа фигур:
#+begin_src cpp 
enum ShapeType {RECTANGLE, CIRCLE, TRIANGLE};

struct Rectangle {
  Point topLeft, bottomRight;
};

struct Circle {
  Point center;
  double radius;
};

struct Triangle {
  Point a,b,c;
};
#+end_src

Другой способ заключается в том, чтобы отказаться от разделения на «форму» и «параметры», и описать тип данных явно и безызбыточно: «либо прямоугольник (задаваемый двумя точками), либо круг (задаваемый точкой и числом), либо треугольник (задаваемый тремя точками)».

Вот код на Haskell:
#+begin_src haskell 
data Shape = Rectangle {topLeft::Point, bottomRight::Point}
           | Circle    {center::Point, radius::Double}
           | Triangle  {a::Point, b::Point, c::Point}
#+end_src

* Сопоставление с образцом (Pattern matching)
Сопоставление формы структуры данных с формой образца и заполнение переменных-«дырок» в образце значениями в соответствующих местах структуры данных.
#+begin_src haskell 
head :: [a] -> a
head [] = error "empty list"
head x:xs = x  
            
reverse xs = reverse' xs []
  where
        reverse' [] r = r
        reverse' (h:t) r = reverse' t (h:r)

processShape :: Shape -> SomeType
processShape Rectangle lft rgt = ...
processShape Circle c r  = ...
processShape Triangle a b c = ...
#+end_src

* Свёртка (Fold)
Вычисление снизу вверх «по индукции», применяющее в каждом узле структуры данных оператор, соответствующий данному типу узла, к содержимому узла и результатам для его подузлов.
Свертки абстрагируют идею вычисления снизу вверх и позволяют компактно записать многие алгоритмы над различными структурами данных, в особенности над списками: почти все стандартные функции обработки списков можно выразить с помощью свертки. Выражая операцию сверткой, программист абстрагируется от деталей обхода структуры данных и задает лишь самые существенные свойства операции: то, как она действует на различные типы узлов структуры, и как комбинирует результаты для подструктур.

* Структурная / вполне обоснованная рекурсия (индукция) (Structural / well-founded recursion (induction))
Рекурсия, при которой аргумент рекурсивного вызова в каком-то смысле строго меньше аргумента исходного.
#+begin_src haskell 
find x Leaf = False
find x (Node a l r)
  | x == a = True
  | x < a = find x l
  | x > a = find x r
#+end_src

Почему мы можем быть уверены, что на всяком конечном дереве вызов этой функции завершается? Потому, что рекурсивный вызов find производится от левой или правой ветви, но нет такого конечного дерева, многократное взятие левой или правой ветви от которого никогда не приводит к листу. Поэтому рано или поздно дерево «закончится», а вместе с ним закончится и дерево рекурсивных вызовов.
Завершимость — самое важное свойство структурно рекурсивных процедур. Некоторые языки программирования, гарантирующие завершаемость программ, обеспечивают ее именно через запрещение всех форм рекурсии, кроме структурной. Кроме того, о структурно-рекурсивных процедурах легко рассуждать математически и доказывать их свойства, поскольку к ним непосредственно применимодоказательство свойства при помощи индукции по аргументу.

Еще один пример: вычисление наибольшего общего делителя.
#+begin_src haskell 
gcd 0 x = x
gcd x 0 = x
gcd a b | a <= b = gcd a (b-a)
        | a > b = gcd (a-b) b
#+end_src

Эта процедура также не является структурно рекурсивной, однако является вполне обоснованно рекурсивной по отношению между аргументами рекурсивного (a', b') и исходного (a, b) вызовов «a’+b’ < a+b», поэтому она гарантированно завершается.

* Класс типов (Type class)
Реализации интерфейсов для типов и их комбинаций указываются в произвольном месте программы и отдельно от определений самих типов.
Классом типов называется именованный набор сигнатур операций, упоминающих этот тип.
Например:
#+begin_src haskell 
class Hashable tau where
  hash :: tau -> Int
  equal :: tau -> tau -> Bool
#+end_src
