* Сайты
https://www.vseti.app/jobs
https://getmatch.ru/
https://geeklink.io/
https://geekjob.ru/
https://career.habr.com/

* Senior Go/Golang Developer/Разработчик
Компания: TQB
ЗП: от 400 000 ₽
Общий стэк проекта: Golang; Database: Postgresql, Clickhouse, Redis; Communication: Rabbitmq, Kafka, grpc, SRE: ELK, Kibana, Grafana, Prometheus, Victoria Metrics; Deploy: gitlab ci, k8s, helm, docker.

- Задачи:
Разрабатывать высокопроизводительные сервисы на GO.

- Ожидания по опыту:
-Опыт разработки от 3-х лет на Golang;
-Опыт работы в проектировании (System design);
-Опыт работы с реляционными базами данных и NoSql решениями;
-Опыт работы с брокерами сообщений;
-Опыт работы на высоконагруженных системах;
-Опыт работы в распределенной команде;
-Уважение, помощь и инициативность в работе со своей командой.

- Условия:
-Оформление: официальное оформление в IT-аккредитованную компанию;
-Формат работы: полностью удаленная работа и/или гибрид и/или работа в современном офисе в центре с бесплатной парковкой, террасой и локациями для игр;
-График работы: офис, удаленка или гибридный формат работы, гибкое начало рабочего дня + 3 day off в год.
Контакты: sales@tqb.expert
* Senior Golang Engineer в команду Отелло
Компания: 2GIS
ЗП: до 550 000 ₽
- Тебе предстоит
-Самостоятельно проектировать технические решения для интеграционных задач разного уровня сложности.
-Делать прототипы и MVP для быстрой проверки продуктовых гипотез, а затем на их основе строить долгосрочное решение для удачных гипотез.
-Брать на себя ответственность за кодовую базу продукта и демонстрировать проактивный подход к улучшению качества архитектуры проекта.
-Демонстрировать структурированный подход к написанию тестов.
-Обеспечивать бесперебойную работу сервиса и заданный уровень SLO.
-Быть примером для подражания для менее опытных коллег и транслировать наши ценности на всю остальную команду.

- Ожидания от кандидата
-У тебя есть опыт проектирования и разработки бэкенд-сервисов от 5 лет на любом языке программирования.
-У тебя есть опыт работы с реляционными и нереляционными БД, с брокерами сообщений.
-Ты ориентирован на решение проблем пользователей и бизнеса, а технологии не являются самоцелью.
-Плюсом будет опыт с: Go, PostgreSQL, Kafka, Elasticsearch, Clickhouse, Kubernetes.
-Даже если ты не соответствуешь всем требованиям, но у тебя есть понимание что мы идеально подходим друг другу - то обязательно оставляй заявку. Возможно, ты как раз идеальный кандидат на эту роль!

- Условия работы
Почему Golang-разработчику хорошо в 2ГИС
-Здесь развита культура разработки на Golang. В 2ГИС вокруг тебя много других Golang-разработчиков, с которыми можно обсуждать интересные тебе темы. Периодически мы делаем внутренние митапы, любим выступать с докладами.
-У нас полноценная команда разработки продукта, в которой есть также frontend и mobile-разработчики, QA-инженеры, дизайнеры, продуктовые и проектные менеджеры.

- Кроме того
-2ГИС — аккредитованная IT-компания.
-Техника и ОС на выбор.
-У нас можно работать удалённо. Для нас важен специалист, а не его локация. Если хочешь работать в гибридном формате, у нас есть офисы в Москве, Санкт-Петербурге, два классных офиса в Новосибирске. А также коворкинги в Томске,  Астане, Алма-Ате.
-Само собой, полностью белая зарплата. Дополнительные дни отпуска за стаж работы в компании.
-Заботимся о здоровье: ДМС и возможность получать онлайн-консультации и терапевта, невролога, психолога и медицинского агента.
-Если хочешь делиться своим опытом, мы только за — поможем с выступлениями на конференциях и статьями для Хабра.
-Есть собственный учебный центр: курсы, тренинги и книги для прокачки скиллов.
Контакты: job@2gis.ru

* Golang разработчик (S3)
окация: Москва
Компания: Сбер
- Обязанности
-Разработка компонент S3-совместимого объектного хранилища на языке
-Go Написание тестов (функциональных и нагрузочных) Code review

- Требования
-Практический опыт разработки на Go или опыт написания системного кода на C/C++ с желанием писать на Go
-Опыт разработки многопоточных приложений
-Опыт проектирования и разработки gRPC/REST API
-Опыт разработки сетевых приложений и понимание стека TCP/IP
-Уверенный пользователь Linux (работа с файлами, ssh, systemctl) Коммуникабельность и общительность.
Приветствуются:
Понимание особенностей построения современных высокодоступных систем Практический опыт использования алгоритмов распределенного консенсуса (Raft, Paxos и др.)
Опыт разработки распределенных систем и представление о схемах репликации и шардирования
Работа с асинхронными, многопоточными и неблокирующими алгоритмами и структурами данных
Опыт системного программирования и низкоуровневой работы с Linux Стэк: Golang, NBD, Linux, SDS, S3.

- Условия
-Гибридный формат работы
-Годовой бонус и ежегодный пересмотр зарплаты
-Статус аккредитованной ИТ-компании со всеми преимуществами
-Расширенный ДМС с первого дня и льготное страхование для семьи
-Корпоративный университет Сбера, внутренняя образовательная платформа, участие в IT-конференциях
-Офис с видом на набережную, зонами отдыха и спортзалом
-90 дней удаленной работы из любого региона
Льготная ипотека в Сбере, подписка СберПрайм+, скидки от партнеров и сервисов группы компаний.
Контакты: https://rabota.sber.ru/search/4388814/

* Разработчик Go (Middle+ / Senior)
Компания: Солар
Мы в поисках талантливого и мотивированного Разработчика Go, который готов присоединиться к нашей команде и внести свой вклад в создание инновационного решения в области кибербезопасности. Если ты стремишься к разработке надежных и эффективных систем, а также хочешь работать в команде единомышленников, тогда это твой шанс! Вместе мы сможем реализовать высокотехнологичный продукт, который сделает мир безопаснее.

Что нужно будет делать:
Писать новые и развивать существующие сервисы на Go;
Участвовать в анализе, проектировании и оценке технических решений вместе с командой;
Писать unit и функциональные тесты;
Участвовать в code review.
Что мы ожидаем:
опыт коммерческой разработки бэкенда на Golang от 4 лет;
опыт работы с SQL базами данных (на уровне join-ов, оптимизации запросов);
умение проектировать высоконагруженные сервисы;
опыт работы с нереляционными базами данных;
опыт работы с Docker, k8s и Git;
опыт работы с брокерами сообщений.
Мы предлагаем:
Официальное оформление в аккредитованную ИТ-компанию со всеми льготами (ипотека, отсрочка и тп);
Конкурентный оклад, премии по результатам работы;
Сильная команда экспертов, которые всегда готовы помочь и поделиться знаниями;
Возможность работать над передовыми продуктами в сфере кибербезопасности;
Перспективы для профессионального и карьерного продвижения;
Корпоративные мероприятия, путешествия, спортивные активности онлайн и оффлайн (онлайн-марафоны, бег, йога, волейбол, лыжи, и др.);
Социальный пакет:
ДМС со стоматологией в лучших клиниках России, возможность подключить родственников по корпоративным ценам;
Доплата больничных до 100% от оклада (28 дней в году), 10 оплачиваемых day-off на случай форс-мажора;
Возможность бесплатного обучения: внешние обучения, профильные конференции, а также наши внутренние курсы и электронная корпоративная библиотека с сотнями книг;
Скидки от компаний-партнеров: спорт, английский, психолог, интернет и многое другое;
Материальная помощь при важных событиях в жизни (заключение брака, рождение детей и другое);
Удаленный формат работы в пределах РФ, либо современный офис рядом с м.Охотный ряд/Савёловская;
График работы: 5/2 с 9:00 до 17:30, либо с 10:00 до 18:30.

* Golang developer/Go-разработчик
#офис #400k
Опыт работы: 3–6 лет
Локация: Санкт-Петербург
Компания: ООО Реддиджитал
ЗП: от 250 000 до 400 000 ₽
🔷Обязанности:
-Разработка кода на GoLang
-Участие в проработке архитектуры продукта
-Решение сложных технических задач, возникающих в ходе реализации продукта
-Рефакторинг и оптимизация кода
-Борьба за миллисекунды

🔷Требования:
-Опыт построения микросервисной архитектуры
-Опыт работы с многопоточностью
-Знание алгоритмов
-Знание языков программирования: GoLang, SQL
-Опыт работы с брокерами-сообщений
-Понимание процесса CI/CD
-Понимание процесса тестирования продукта
-Опыт применения гибкой методологии разработки
-Хорошие коммуникационные навыки
Будет плюсом:
-Опыт в разработке высоконагруженных продуктов
-Опыт в разработке продуктов для Digital Рекламы
-Опыт работы с NoSQL (Redis, MongoDB, ElasticSearch, Memcached)
-Опыт работы с БД ClickHouse
-Опыт работы с БД Aerospike
-Опыт работы с Docker и Kubernetes
-Базовые знания Python/R + опыт/понимание анализа данных

🔷Условия:
-Официальное оформление в аккредитованную IT компанию
-Комфортная офисная работа 5/2 в БЦ Сенатор (массажное кресло, кофе, чай, печеньки, всё для завтрака)
-Формат работы - офис, 5/2, плавающие начало и окончание рабочего дня
-ДМС после испытательного срока
-Бонусы по итогам работы
-Насыщенная корпоративная жизнь
Контакты: hr@reddigital.video

* Golang-разработчик
#удаленкарф #senior #500k
Компания: Точка
ЗП: до 520 000₽
🔷Что делать
— Разрабатывать клиентский и интеграционный API для интернет-банка: создавать документы, подписывать их и другие возможности.
— Развивать и поддерживать сервисы для документооборота, такие как работа с криптографией и создание печатных форм.
— Развивать электронный документооборот как инфраструктурный SaaS-сервис, которым могут пользоваться другие команды Точки.
— Создавать платформу по взаимодействию Точки с другими операторами электронного документооборота в России.
— Участвовать в запуске новых сервисов, в том числе выходящих за рамки платформы интернет-банка.
— Работать вместе с продакт-менеджером и системным аналитиком над продуктовыми планами: проверять требования, проектировать архитектуру для сложных бизнес-задач, следить за качеством и поддерживаемостью кода.
— Участвовать в двухнедельных дежурствах вместе с командой Сопровождения. Продуктовых задач не будет, нужно выступать как третья линия поддержки для разбора и устранения сложных ситуаций и ошибок в работе сервисов.
— Предлагать улучшения и автоматизации админки и тулинга для решения типовых проблем.

🔷Наш стек
— У нас микросервисная архитектура.
— Используем Golang 1.22
— Храним данные в PostgreSQL.
— Реализуем асинхронное взаимодействие на RabbitMQ.
— Используем TeamCity, GitLab для CI/CD.
— Разворачиваем сервисы в Docker.
— Проводим мониторинг на Prometheus, Grafana, Sentry.
— Заботимся о качестве кода: проводим ревью, всё покрываем тестами и даём обратную связь.
— Используем Agile, SCRUM и OKR.

🔷Ты подойдёшь, если
— Есть опыт коммерческой разработки на Golang от 3 лет.
— Умеешь писать читаемый код.
— Знаешь, как работать с реляционными базами данных.
— Знаешь Git, CI и CD.
— Можешь работать с Docker, виртуализацией, контейнеризацией.
— Есть опыт работы с очередями.
— Можешь самостоятельно организовать работу и выполнять задачи без постоянного контроля.
— Легко находишь общий язык с людьми и умеешь понятно объяснять сложные вещи.

🔷Будет плюсом
— Опыт управления командой, декомпозиции задач для новых проектов и развития продукта.
— Опыт работы в доменной области электронного документооборота в РФ.
— Умеешь выстраивать архитектуру нагруженных систем и оптимизации больших баз данных.
Контакты: ‍https://tochka.com/hr/it/golang-developer/

* Senior GO разработчик
#удаленка #senior #400k
Опыт работы: более 6 лет
Компания: Hi, Rockits!
ЗП: от 400 000 ₽
🔷Чем предстоит заниматься:
-Проектирование архитектуры и сервисов для приложений B2C и B2B
-Обеспечение отказоустойчивости разработанных сервисов в среде Digital Ocean
-Разработка и улучшение бэкэнд-сервисов для поддержки роста торговой платформы
-Создание сервиса с высоким трафиком и большим количеством пользователей и объектов взаимодействия
-Участие в обсуждениях новых функций и разработки продукта
Go: 1.18+
Logging: zero log, slog
Работать с БД: PostgreSQL, Clickhouse; Redis; GORM

🔷Вы точно подойдете на эту вакансию, если имеете:
-Опыт работы в DeFi
-Более пяти лет опыта коммерческого программирования на Go
-Опыт работы с горутинами и их отладки
-Опыт написания модульных и интеграционных тестов
-Понимание архитектуры микросервисов
-Опыт разработки с API REST и API gRPC
-Опыт работы с брокерами: Kafka, NATS или похожими
-Опыт работы с системой контроля версий Git
-Опыт и понимание принципов CI/CD
-Понимание контейнеризации, виртуализации и технологий Serverless
-Знакомство с системами управления облаком (инструментарий, предоставление, выставление счетов и квоты)
-Опыт написания скриптов с Bash, Python, Gotemplate
-Опыт автоматизации развертывания инфраструктуры с использованием одного или нескольких инструментов (Ansible, Terraform, Pulumi)
-Опыт работы с системами мониторинга, такими как Zabbix, Prometheus и другими

🔷Что предлагает компания:
-отсутствие привязки к локации, можно работать из любой точки мира
-оформление любым удобным способом (в том числе можно и по ТК РФ)
-широкая вилка выше рынка
-профессиональное развитие в highload и web3 пространствах
годовые бонусы и акции на основе производительности и достигнутых результатов

🔷Как будет выглядеть процесс коммуникации:
1. Встреча с рекрутером на 15 минут
2. Лайвкодинг
3. Техническое интервью в формате диалога с разработчиком — 1,5 часа
*при необходимости дополнительная встреча с разработчиком
4. Интервью на soft skills с руководителем разработки — 1 час
Оффер!
Контакты: jukislitsyna@rockits.ru

* Senior Go developer (Data Processing & File Storage Development)
#офис #senior
Компания: Kaspersky
🔷Обязанности
-Разработка, поддержка и мониторинг распределённых систем обработки данных.
-Разработка интеграционных и юнит-тестов.
-Анализ требований, участие в разработке планов и оценке реализации.
-Активное участие в выборе и проработке технологий.
-Проведение кодревью.

🔷Требования:
-Опыт программирования на Go.
-Понимание принципов ООП.
-Опыт разработки распределённых систем обработки информации: работа с БД, кэшами, очередями.
-Опыт работы с git.
-Понимание методик юнит-тестирования.
-Опыт работы с Linux на уровне опытного пользователя.
-Знание основ сетей.

🔷Будет плюсом:
-Знание или опыт работы с C/C++, Python, Java, Scala.
-Опыт работы с большими данными и нагрузками, понимание связанных с этим проблем и умение их решать.
-Опыт работы с любым из инструментов обработки данных: Spark, Hadoop, Kudu, Kafka, Airflow.
-Опыт с NoSQL решениями: Elasticsearch, Redis, ScyllaDB.
-Опыт построения вычислительных кластеров на базе Mesos/Kubernetes/и т.д.
-Опыт с deploy инструментами Ansible/Puppet/Chef, Docker и т.д.
-Понимание основ информационной безопасности.
Контакты: https://careers.kaspersky.ru/vacancy/22887
