#+title: System Design Топ 5 Ошибок Новичка На Интервью

https://habr.com/ru/articles/907712/

* Посмотрите на них и никогда не повторяйте!
- Бессистемный подход вместо чёткого алгоритма
- Преждевременное решение без уточнения требований
- Недопустимое упование на уже оформленные требования
- Неструктурированная коммуникация, которая сбивает интервьюера
- Отсутствие ревью своей системы

=Почему даже подготовленные кандидаты проваливаются?=
Раньше System Design спрашивали только у senior backend-разработчиков. Сегодня - у аналитиков, продакт-менеджеров и даже SRE.
Парадокс: при огромной доступности информации (Хабр, англоязычные гайды, шаблоны масштабирования) кандидаты массово наступают на одни и те же грабли.

=Почему?=
- Информационный перегруз - книги, сотни статей с многообразным материалом и ссылками в ссылках
- Отсутствие системы - без четкого фреймворка прохождения легко утонуть в деталях или сбиться с верного пути
- Стресс-фактор - даже зная теорию, можно забыть основу под давлением

* Поговорим про жизнь, а потом само пойдёт
На самом деле есть чёткий алгоритм прохождения интервью, которому нужно следовать:
- =Уточнить требования=
- =Расписать API=
- =Нарисовать верхнеуровневую схему=
- Расписать модель данных
- Словить deep dive в какую-то часть системы
- Поговорить о масштабировании
- Аргументировать технологии
- Сказать о мониторинге
- Подытожить

* Мне дали проектировать ленту. Я прекрасно знаю требования!
Да, вы могли изучить эту бедную ленту вдоль и поперёк. Прочитать Сью, Кабанчика, пообщаться с разработчиками твиттер, вк, изобрести собственный фасбук и совершенно спокойно пробежать эту очевидную вещь - уточнение требований.

Даже если вы знаете задачу, видели и прорабатывали решение, узнайте, что именно нужно проектировать в рамках этой сессии интервью.

* Да тут всё расписано!
Перепишите требования в понятной для вас форме

Например в use cases.
Сводим функциональные требования к системе, к тем действиям, которые пользователи могут над ней производить.
К тому же это прекрасно перекладывается в API методы.

* Вариантов развития сюжета много. Куда свернуть?
Между этапами, и для выяснения следующих существует магическая фраза. Её можете высечь в камне. Повесить над перед собой готовясь к System Design Интервью:

"Я описал базово API. Если этого достаточно, предлагаю идти дальше проектировать схему."

Почему фраза прекрасна и прокладывает вам дорожку к успешному прохождению? Секрет прост.
Она несёт в себе сообщения:
- Я понимаю что делаю
- Я понимаю ограниченный тайминг интервью
- Я пониманию, что можно многое обсудить. И на каждом интервью можно пойти либо широко. Либо куда-то углубиться
- Мы с тобой имитируем рабочую ситуацию. Коммуницируем как колеги. Мне интересно твоё мнение. Ты же, фактически, заказчик
- Я прохожу интервью инициативно

* Silent end
Делать выводы между этапами и в конце.
Даже если не хватает компонента, вы успеваете описать его словами. Этого может быть достаточно.
