#+title: Шардирование

* Партиционирование
Метод разделения больших таблиц на много маленьких =прозрачным= и понятным способом.
=Прозрачный= - значит, что клиент не понимает, что таблица разделена.
При этом секции находятся на одном инстансе БД.
Типы:
+ вертикальное - по колонкам
+ горизонтальное - по строкам

* Шардирование
Партичионирование на разных инстансах или машинах.
Шардирование используется с репликацией, чтобы не потерять данные.

* Способы шардирования
+ range based - по интервалам какого-либо ключа
+ key based - по значению ключа какого-либо ключа
+ directory based - напрямую руками указывая шард для ключа.

* Роутинг (routing)
Опредение направления - в какой шард идти клиенту.
+ Клиентский - логика выбора шарда прописана в клиенте
  "+" - нет лишних узлов
  "-" - доп. логика на клиенте, сложности с добавлением хостов.
+ Proxy - добавление узла, который выполняет роутинг
  "+" - прозрачность для клиента
  "-" - доп. сетевой узел, единая точка отказа, потеря функциональности (сложные запросы с данными из разных шардов не протащить)
+ Coordinator - proxy с логикой. Может выполнять сложные запросы, кэшировать данные и тд.
  "+" - кэш и сложные запросы возможны
  "-" - доп. сетевой узел, единая точка отказа, инфраструктурная сложность, высокая нагрузка на этот узел.

* Перебалансировка
Перенос данных между шардами.
Варианты, как это делать:
+ запрещать запись, простой сервиса
+ все данные не изменяемы
+ логическая репликация данных и переключение на реплику
+ смешанный

* Resharding
Если нужно добавить еще шарды или наоборот удалить. Или сменить подход к шардированию.
+ consistent hasing - номера шардов располагаются по кругу (как часы) и номера между шардами идут по часовой стрелке в следующий шард.
 Что плохого:
  - неравномерное распределение
  - данные могут быть несбалансированы и может начаться цепная реакция падений
Решение - виртуальные шарды. На каждый шард делается несколько виртуальных и нагрузка распределяется между ними двумя.
+ randezvous (рандеву) hasing - делается хэш-функция в которую подмешивается как соль номер виртуального шарда и конкретный виртуальный шард выбирается по значению этой функции.
