#+title: Cte Общее Табличное Выражение И Их Использование

=CTE= (Общее Табличное Выражение) — этовременный набор результатов, который определяется в рамках выполнения одного оператора (SELECT, INSERT, UPDATE или DELETE).
=CTE= позволяют упрощать выполнение сложных запросов, делая их более читаемыми и поддерживаемыми.

~Характеристики CTE~

=CTE= могут материализоваться в памяти в ходе выполнения запроса, что позволяет избежать повторного выполнения одного и того же SQL запроса, если он используется несколько раз в основном запросе.

~Синтаксис~

#+begin_src sql
WITH CTE_Name AS (
    SELECT column1, column2
    FROM table_name
    WHERE condition
)
SELECT *
FROM CTE_Name;
#+end_src

~Преимущества CTE~

- Читаемость
  ~CTE~ упрощают сложные запросы, разбивая их на логически связанные части, что делает код легче воспринимаемым.
- Избежание многократного выполнения
  Если один и тот же набор данных требуется в нескольких местах в запросе, использование ~CTE~ позволяет материализовать результаты один раз и использовать их множество раз без повторной выборки из базы данных, что приводит к более эффективному выполнению.
- Рекурсия
  ~CTE~ поддерживают рекурсивные запросы, что позволяет выполнять сложные иерархические запросы (например, при работе с родительскими и дочерними записями).
- Модульность
  ~CTE~ помогают инкапсулировать логику, что делает её повторно используемой в рамках одного запроса, а также упрощает поддержку и изменение SQL кода.

~Когда использовать CTE~

- При работе с сложными соединениями или множеством агрегаций, где повторное выполнение одной и той же подзадачи может значительно снизить производительность.
- В ситуациях, когда необходимо создать рекурсивный запрос (например, для извлечения данных из иерархической структуры).
- Для повышения читаемости и структурированности запросов, особенно если они содержат несколько уровней вложенности.
