#+title: Что Такое False Sharing

Когда несколько горутин или потоков изменяют разные переменные, которые физически располагаются в одной и той же кэш-линии, это может вызвать лишние кэш-неэффективности и снижение производительности, потому что процессор будет постоянно сбрасывать или обновлять кэш каждой горутины, даже если они работают с разными переменными.

Как избежать =false sharing=:
1. =Разделение данных=
   чтобы минимизировать false sharing, можно разместить данные, которыми часто пользуются разные горутины или потоки, в разные кэш-линии. Для этого в Go можно использовать =padding= (добавление пустых полей в структуру) или =memory alignment= (выравнивание данных по границе кэш-линии).

2. =Использование более мелких блоков данных=
   если возможно, лучше разделить общие данные на более мелкие блоки, чтобы они не попадали в одну кэш-линию.

3. =Использование атомарных операций=
   в некоторых случаях можно использовать атомарные операции для предотвращения пересылки данных между процессами, так как они могут помочь снизить нагрузку на кэш.
